### ISSUE TITLE
感谢

### ISSUE THREAD

**Issue by hellomaya** [GDGNanyang/studyjam#2]
感谢你介绍的访问google服务的方法。
如果可以，我可以帮忙翻译，虽然我不学习Android，不过曾经做过不到一年的安卓。
需要留言好了，一直在github上。

**Comment by chenglu** [comment]
这里有一份[工作指南](https://www.gdgdocs.org/document/d/1CvqhM0BBO9xGOL6AL9nBcHnTAmMPY7mnN10BTWR0xC8/pub)，看一下，如果可以，我就给你分配工作，暂时分配的任务是 Lession2 的 21 ~ 24，同样的，如果第二天有工作临时不能做事的话，就提前通知我哈。

**Comment by hellomaya** [comment]
好的，我今天把它翻译出来，不过后面未必有时间，所以提前说一下，如果有时间我会再次告诉你，工作忙，事情多，呵呵，谢谢理解～，粗略翻译了一下，稍后在查看下视频，校对一下。

**Comment by chenglu** [comment]
辛苦了亲 @hellomaya
